# Generated by Django 5.0.1 on 2024-01-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "doi",
                    models.CharField(
                        db_index=True, max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("pmid", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("topic", models.CharField(max_length=100)),
                ("abstract_text", models.TextField()),
                ("publication_type", models.CharField(max_length=200)),
                ("journal_title", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("month", models.CharField(max_length=20)),
                ("citations", models.IntegerField(default=0)),
                ("influential_citations", models.IntegerField(default=0)),
                ("basic_science", models.BooleanField(default=False)),
                ("trial", models.BooleanField(default=False)),
                ("machine", models.BooleanField(default=False)),
                ("observational", models.BooleanField(default=False)),
                ("guideline", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Impact",
            fields=[
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="vetu.paper",
                    ),
                ),
                ("citations", models.IntegerField(default=0)),
                ("impactful_citations", models.IntegerField(default=0)),
                ("meaningful", models.BooleanField(default=False)),
                ("citation_data", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("orcid_id", models.CharField(blank=True, max_length=100, null=True)),
                ("affiliation", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vetu.paper"
                    ),
                ),
            ],
        ),
    ]
