# Generated by Django 5.0.1 on 2024-01-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0002_paper_affiliations_paper_affiliations_checked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="year",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
