# Generated by Django 5.0.1 on 2024-01-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0003_alter_paper_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="paper_fill",
            field=models.BooleanField(default=False),
        ),
    ]
