# Generated by Django 5.0.1 on 2024-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0004_paper_paper_fill"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("ORCID", models.CharField(max_length=20)),
                ("Citations", models.IntegerField(default=0)),
                ("Impactful_Citations", models.IntegerField(default=0)),
                ("h_index", models.IntegerField(default=0)),
            ],
        ),
    ]
