# Generated by Django 5.0.1 on 2024-01-19 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0006_rename_citations_authorimpact_citations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorimpact",
            old_name="impactful_Citations",
            new_name="impactful_citations",
        ),
    ]
