# Generated by Django 5.0.1 on 2024-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0007_rename_impactful_citations_authorimpact_impactful_citations"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="authors_checked",
            field=models.BooleanField(default=False),
        ),
    ]
