# Generated by Django 5.0.1 on 2024-01-23 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0008_paper_authors_checked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="orcid_id",
            new_name="identifier",
        ),
    ]
