# Generated by Django 5.0.1 on 2024-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0009_rename_orcid_id_author_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorimpact",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="authorimpact",
            name="orcid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
