# Generated by Django 5.0.1 on 2024-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0010_alter_authorimpact_name_alter_authorimpact_orcid"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorimpact",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
