# Generated by Django 4.2.9 on 2024-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0013_remove_paper_citations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="affiliation",
            field=models.CharField(max_length=1000),
        ),
    ]
