# Generated by Django 4.2.9 on 2024-02-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0017_alter_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="topic",
            field=models.CharField(max_length=600),
        ),
    ]
