# Generated by Django 4.2.9 on 2024-02-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0019_alter_paper_topic_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="journal_title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="paper",
            name="publication_type",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="paper",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
