# Generated by Django 5.0.4 on 2024-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vetu", "0022_alter_paper_affiliation_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="affiliation_codes",
            field=models.TextField(default="None"),
        ),
    ]
