# Generated by Django 4.2.9 on 2024-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('doi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pmid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
