# Generated by Django 5.0.1 on 2024-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="main",
            name="pmid",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
