# Generated by Django 4.2.9 on 2024-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='citations',
            field=models.IntegerField(default=0),
        ),
    ]
