# Generated by Django 4.2.9 on 2024-01-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_papers_citations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('orcid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(max_length=200)),
                ('citations', models.IntegerField(default=0)),
                ('influential_citations', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('doi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pmid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('abstract_text', models.TextField()),
                ('publication_type', models.CharField(max_length=200)),
                ('journal_title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('citations', models.IntegerField(default=0)),
                ('influential_citations', models.IntegerField(default=0)),
                ('basic_science', models.BooleanField(default=False)),
                ('trial', models.BooleanField(default=False)),
                ('machine', models.BooleanField(default=False)),
                ('observational', models.BooleanField(default=False)),
                ('guideline', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='papers',
            name='main',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
        migrations.AddField(
            model_name='author',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.paper'),
        ),
    ]
