# Generated by Django 5.0.1 on 2024-01-09 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0004_impact_alter_paper_doi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="citations",
        ),
        migrations.RemoveField(
            model_name="author",
            name="h_index",
        ),
        migrations.RemoveField(
            model_name="author",
            name="influential_citations",
        ),
    ]
