# Generated by Django 5.0.1 on 2024-01-15 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0005_remove_author_citations_remove_author_h_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impact",
            name="h_index",
        ),
    ]
