# Generated by Django 5.0.1 on 2024-01-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0006_remove_impact_h_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="citation_data",
            field=models.JSONField(default=dict),
        ),
    ]
