# Generated by Django 5.0.1 on 2024-01-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0007_impact_citation_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
