# Generated by Django 5.0.1 on 2024-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0009_alter_impact_citation_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impact",
            name="citation_data",
            field=models.JSONField(default=dict),
        ),
    ]
